WebServer/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebServer;
using WebServer.Models;

namespace WebServer.Controllers
{
    [Authorize(Roles = "Администратор")]
    public class AdminController : Controller
    {
        private readonly AppDbContext _context;

        public AdminController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin
        public async Task<IActionResult> Index()
        {
            var users = await _context.Users.ToListAsync();
            var claims = await _context.UserRoleClaims.ToListAsync();
            List<UserData> data = new List<UserData>();
            foreach (var user in users)
            {
                data.Add(new UserData(user, claims.Find(x => x.User_Id == user.User_Id)));
            }
            return View(data);
        }

        // GET: Admin/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.User_Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Admin/Create
        public async Task<IActionResult> CreateAsync()
        {
            var roles = await _context.Roles.ToListAsync();
            ViewBag.RoleList = new SelectList(roles, "Role_Id", "Role_Name");
            var groups = await _context.Groups.ToListAsync();
            ViewBag.GroupList = new SelectList(groups, "Group_Id", "Group_Number", null, "Year");
            ViewBag.Claim = new UserRoleClaim();
            ViewBag.Student = new Student();
            if (roles == null)
            {
                return NotFound();
            }
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Login,Password,Email,Active")] User user, UserRoleClaim claim, Student student)
        {
            if (ModelState.IsValid)
            {
                user.Active = false;
                _context.Add(user);
                await _context.SaveChangesAsync();
                claim.User_Id = user.User_Id;
                _context.Add(claim);
                await _context.SaveChangesAsync();
                if (claim.Role_Id == 1)
                {
                    await _context.SaveChangesAsync();
                    student.User_Id = user.User_Id;
                    _context.Add(student);
                    await _context.SaveChangesAsync();
                }
                else if (claim.Role_Id == 2)
                {
                    // Создаем запись в таблице Profs только для преподавателей
                    Prof prof = new Prof
                    {
                        User_Id = user.User_Id,
                        // Другие свойства, если есть
                    };
                    _context.Add(prof);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Admin/Groups
        public async Task<IActionResult> Groups()
        {
            var groups = await _context.Groups.ToListAsync();
            var teaches = await _context.Profs.ToListAsync();
            var users = await _context.Users.ToListAsync();
            List<GroupData> data = new List<GroupData>();
            foreach (var group in groups)
            {
                data.Add(new GroupData(group, users.Find(y => y.User_Id == teaches.Find(x => x.Teacher_Id == group.Teacher_Id).User_Id).Name));
            }
            return View(data);
        }

        // GET: Admin/CreateGroup
        public async Task<IActionResult> CreateGroupAsync()
        {
            var teachers = await _context.Profs.ToListAsync();
            List<ProfData> TeacherList = new List<ProfData>();
            foreach (var teacher in teachers)
            {
                TeacherList.Add(new ProfData(teacher.Teacher_Id, _context.Users.FirstOrDefaultAsync(m => m.User_Id == teacher.User_Id).Result.Name));
            }
            ViewBag.TeacherList = new SelectList(TeacherList, "Teacher_Id", "Teacher_Name");
            return View();
        }

        // POST: Admin/CreateGroup
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateGroup([Bind("Group_Number,Teacher_Id,Year,Specialty")] Group group)
        {
            if (ModelState.IsValid)
            {
                _context.Add(group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Groups));
            }
            return View();
        }

        // GET: Admin/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("User_Id,Name,Login,Password,Email,Active,Role_Id")] User user)
        {
            if (id != user.User_Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.User_Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Admin/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.User_Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.User_Id == id);
        }
    }
}

WebServer/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebServer;
using WebServer.Models;

namespace WebServer.Controllers
{
    public class StudentController : Controller
    {
        private readonly AppDbContext _context;

        public StudentController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Student
        public async Task<IActionResult> Index()
        {
            var user = await _context.Users.FirstOrDefaultAsync(m => m.Name == User.Identity.Name);
            var stud = await _context.Students.FirstOrDefaultAsync(m => m.User_Id == user.User_Id);
            List<LabworkData> labworks = new List<LabworkData>();
            foreach (var item in await _context.Labworks.Where(l => l.Student_Id == stud.Student_Id).ToListAsync())
            {
                labworks.Add(new LabworkData(await _context.Labs.FirstOrDefaultAsync(x => x.Lab_Id == item.Lab_Id), item));
            }
            return View(labworks);
        }

        // GET: Student/Labs
        public async Task<IActionResult> Labs()
        {
            return View(await _context.Labs.OrderBy(m => m.Lab_Name).ToListAsync());
        }
    }
}

WebServer/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebServer.Models;

namespace WebServer.Controllers
{

    [Authorize(Roles = "Преподаватель")]
    public class TeacherController : Controller
    {
        private readonly AppDbContext _context;

        public TeacherController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Teacher/Labs
        public async Task<IActionResult> LabsAsync()
        {
            return View(await _context.Labs.ToListAsync());
        }

        // GET: Teacher/Journal
        public async Task<IActionResult> JournalAsync()
        {
            var students = await _context.Students.ToListAsync();
            var users = await _context.Users.ToListAsync();
            List<StudData> data = new List<StudData>();
            foreach (var stud in students)
            {
                data.Add(new StudData(stud.Group_Id, users.FirstOrDefault(x => x.User_Id == stud.User_Id).Name));
            }
            ViewBag.StudData = data.OrderBy(x => x.Name);
            ViewBag.Labs = await _context.Labs.ToListAsync();
            return View(await _context.Labworks.ToListAsync());
        }

        // GET: Teacher/AddLab
        public async Task<IActionResult> AddLabAsync()
        {
            return View();
        }

        // POST: Teacher/AddLab
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddLab([Bind("Lab_Name,Steps,Description")] Lab lab)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lab);
                await _context.SaveChangesAsync();
            }
            return Redirect("/Teacher/Labs");
        }
    }
}

WebServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Виртуальная лаборатория</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @{
        var isAuthenticated = User.Identity.IsAuthenticated;
    }
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Виртуальная лаборатория</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (isAuthenticated)
                        {
                            @if (User.IsInRole("Студент"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Выполненные работы</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Labs">Лабораторные работы</a>
                                </li>
                            }
                            else if (User.IsInRole("Преподаватель"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Labs">Лабораторные работы</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Journal">Журнал</a>
                                </li>
                            }
                            else if (User.IsInRole("Администратор"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Пользователи</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Groups">Группы</a>
                                </li>
                            }
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (isAuthenticated)
                        {
                            <li class="nav-item">
                                 <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Profile">Привет, @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <form id="logoutForm" asp-controller="User" asp-action="Logout" method="post" class="form-inline">
                                    <button type="submit" class="btn btn-link text-dark">Выйти</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="User" asp-controller="User" asp-action="Login">Войти</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Виртуальная лаборатория
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>